Sprint 3
devBaxa/middle.messenger.praktikum.yandex pull request #5
Opened 2022-03-11 23:40 UTC by devBaxa

2022-03-13 11:29 UTC, ua9msn commented on src/api/chats.ts
> +                const array = JSON.parse(res);
Плохая практика называть переменные абстрактными именами. Здесь может быть `rawChartResponse` например

2022-03-13 11:33 UTC, ua9msn commented on src/api/chats.ts
> +}
В общем это выглядит как плохая архитектура. В одной функции вы запрашиваете сервер, ищете дом узлы, создаете слушателей, и игноририруете возможные ошибки.

2022-03-13 11:33 UTC, ua9msn commented on src/api/chats.ts
> +    const chatNumber = obj!.getAttribute('chat-id');
Как и выше, не называйте переменные абстрактными именами

2022-03-13 12:18 UTC, ua9msn commented on src/api/userUpdate.ts
> +        settingsProps.formControls[5].value = json.phone;
Тоже плохая практика устанавливать переменные другого модуля напрямую. Следует использовать сеттеры.

2022-03-13 12:21 UTC, ua9msn commented on src/components/linkLogout/index.ts
> +        if (res === "OK") {
Таокй ответ от сервера учше нитерпретировать по статусу 200=ОК 500=ERR итд. Не завязывайтесь на конкретное сообщение

2022-03-13 12:24 UTC, ua9msn commented on src/modules/Route.ts
> +    protected _props: PropsType;
Почему эти переменные объявлены как `protectded`? Предполагается что насленики смогут их переопределить? Не лучше ли использовать `private`?

2022-03-13 12:38 UTC, ua9msn commented on src/modules/Router.ts
> +                            router.go('/messenger');
Неявное переопределение маршрута. Роут должен сам с этим справляться, например при помощи алиасов.

2022-03-13 12:51 UTC, ua9msn commented on src/pages/changePassword/index.ts
> +                let obj = checkAllInputs();
`event` имеет тип `Event` Пользуйтесь стандартными типами где можно

2022-03-13 12:52 UTC, ua9msn commented on src/pages/changeSettings/changeSettings.tpl.ts
> +<div class="form-control not-empty">
Что то с форматированием? Нет отступов

2022-03-13 13:16 UTC, ua9msn requested changes
Некоторые места следует переделать

2022-03-16 08:12 UTC, ua9msn commented on src/api/chats.ts
> +                const array = JSON.parse(res);
H

2022-03-16 08:22 UTC, devBaxa commented on src/api/chats.ts
> +                const array = JSON.parse(res);
Привет, resolved.

2022-03-16 08:23 UTC, devBaxa commented on src/api/chats.ts
> +}
Разбил на несколько функций. Добавил проверку на ошибки.

2022-03-16 08:23 UTC, devBaxa commented on src/api/chats.ts
> +    const chatNumber = obj!.getAttribute('chat-id');
resolved

2022-03-16 08:24 UTC, devBaxa commented on src/api/userUpdate.ts
> +        settingsProps.formControls[5].value = json.phone;
добавил сеттер для settingsProps.

2022-03-16 08:25 UTC, devBaxa commented on src/components/linkLogout/index.ts
> +        if (res === "OK") {
В HTTPTransport() уже есть проверка на статус, поэтому лишнюю проверку if (res === "OK") убрал, т.к. до сюда не дойдёт при ошибке.

2022-03-16 08:25 UTC, devBaxa commented on src/modules/Route.ts
> +    protected _props: PropsType;
resolved

2022-03-16 08:25 UTC, devBaxa commented on src/modules/Router.ts
> +                            router.go('/messenger');
перенёс проверку на авторизованного пользователя из Router.ts
resolved

2022-03-16 08:26 UTC, devBaxa commented on src/pages/changePassword/index.ts
> +                let obj = checkAllInputs();
Везде подправил, resolved

2022-03-16 08:26 UTC, devBaxa commented on src/pages/changeSettings/changeSettings.tpl.ts
> +<div class="form-control not-empty">
resolved

2022-03-16 11:36 UTC, ua9msn approved these changes

2022-03-16 11:36 UTC, ua9msn commented on src/api/chats.ts
> +    const arrayChats = JSON.parse(rawChatResponse);
Здесь должен быть тип. Что то вроде 
`const chats: Chat[] = JSON.parse(rawChatResponse)`
Тогда не придется делать `ts-ignore`
И желательно оборачивать `JSON.parse` в `try catch` , мало что там придет

2022-03-16 11:36 UTC, ua9msn commented on src/api/chats.ts
> +            chatsBlockProps.chatList.push(itemObj);
Все равно не даете переменным понятные имена. `itemObj` По коду видно, что это что то о чате и последнее сообщение. Но приходится вчитываться. Можно было бы назвать ее `chatInfo`, было бы лучше

2022-03-16 11:36 UTC, ua9msn commented on src/api/chats.ts
> +}
По коду выше. Смешивать работу с сетью и с DOM даже в одном файле плохо, не то что в одной функции. 
Я пропущу это, но в реальных проектах так не пройдет.

2022-03-16 11:36 UTC, ua9msn commented on src/api/userUpdate.ts
> +        inputPhoneProps.value.text = json.phone;
Здесь не исправлно. Присваивание значений переменным в другом модуле в конечном счете превращает код в кашу. Постарайтесь этого избегать. Лучше создать там метод для установки переменных и передавать в него данные. Пропущу что бы вас не задерживать

2022-03-16 11:44 UTC, devBaxa commented on src/api/userUpdate.ts
> +        inputPhoneProps.value.text = json.phone;
понял, пропустил это. Т.е. при изменении данных в объекте лучше всего использовать setter?

2022-03-16 11:46 UTC, devBaxa commented on src/api/chats.ts
> +    const arrayChats = JSON.parse(rawChatResponse);
Спасибо, исправлю у себя.

2022-04-06 22:39 UTC, merged